// Generated by npm run plugins:sync. Do not edit manually.
import preview0 from '../Navbar.plugin/preview.svg?url' // Navbar
import preview1 from '../Hero.plugin/preview.svg?url' // Hero
import preview2 from '../FAQ.plugin/preview.svg?url' // FAQ
import preview3 from '../Features.plugin/preview.svg?url' // Features
import preview4 from '../Gallery.plugin/preview.svg?url' // Gallery
import preview5 from '../Product.plugin/preview.svg?url' // Product
import preview6 from '../Specifications.plugin/preview.svg?url' // Specifications
import preview7 from '../Steps.plugin/preview.svg?url' // Steps
import preview8 from '../CTA.plugin/preview.svg?url' // CTA
import preview9 from '../Footer.plugin/preview.svg?url' // Footer

export const pluginPreviewImages = {
  Navbar: preview0,
  Hero: preview1,
  FAQ: preview2,
  Features: preview3,
  Gallery: preview4,
  Product: preview5,
  Specifications: preview6,
  Steps: preview7,
  CTA: preview8,
  Footer: preview9,
} as const
