// Generated by npm run plugins:sync. Do not edit manually.
import preview0 from '../Navbar.plugin/preview.svg?url' // Navbar
import preview1 from '../Hero.plugin/preview.svg?url' // Hero
import preview2 from '../FAQ.plugin/preview.svg?url' // FAQ
import preview3 from '../Features.plugin/preview.svg?url' // Features
import preview4 from '../Gallery.plugin/preview.svg?url' // Gallery
import preview5 from '../Product.plugin/preview.svg?url' // Product
import preview6 from '../Specifications.plugin/preview.svg?url' // Specifications
import preview7 from '../Steps.plugin/preview.svg?url' // Steps
import preview8 from '../CTA.plugin/preview.svg?url' // CTA
import preview9 from '../Footer.plugin/preview.svg?url' // Footer

export const pluginCatalog = [
  {
    manifest: {
      id: 'navbar',
      name: 'Navbar',
      category: 'Navigation',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'header',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'links', type: 'list', required: true },
      ],
    },
    previewImage: preview0,
  },
  {
    manifest: {
      id: 'hero',
      name: 'Hero',
      category: 'Hero',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'hero',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'actionLabel', type: 'text', required: true },
        { name: 'actionHref', type: 'url', required: false },
      ],
    },
    previewImage: preview1,
  },
  {
    manifest: {
      id: 'faq',
      name: 'FAQ',
      category: 'FAQ',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'questions', type: 'list', required: true },
      ],
    },
    previewImage: preview2,
  },
  {
    manifest: {
      id: 'features',
      name: 'Features',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'items', type: 'list', required: true },
      ],
    },
    previewImage: preview3,
  },
  {
    manifest: {
      id: 'gallery',
      name: 'Gallery',
      category: 'Media',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'images', type: 'list', required: true },
      ],
    },
    previewImage: preview4,
  },
  {
    manifest: {
      id: 'product',
      name: 'Product',
      category: 'Commerce',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
      ],
    },
    previewImage: preview5,
  },
  {
    manifest: {
      id: 'specifications',
      name: 'Specifications',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'specifications', type: 'list', required: true },
      ],
    },
    previewImage: preview6,
  },
  {
    manifest: {
      id: 'steps',
      name: 'Steps',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'items', type: 'list', required: true },
      ],
    },
    previewImage: preview7,
  },
  {
    manifest: {
      id: 'cta',
      name: 'CTA',
      category: 'Conversion',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'conversion',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'actionLabel', type: 'text', required: true },
        { name: 'actionHref', type: 'url', required: false },
      ],
    },
    previewImage: preview8,
  },
  {
    manifest: {
      id: 'footer',
      name: 'Footer',
      category: 'Footer',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'footer',
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'links', type: 'list', required: true },
      ],
    },
    previewImage: preview9,
  },
] as const
