// Generated by npm run plugins:sync. Do not edit manually.
import { validateNavbarContent } from '../Navbar.plugin/admin/navbarContent.ts'
import { validateHeroContent } from '../Hero.plugin/admin/heroContent.ts'
import { validateFAQContent } from '../FAQ.plugin/admin/faqContent.ts'
import { validateFeaturesContent } from '../Features.plugin/admin/featuresContent.ts'
import { validateGalleryContent } from '../Gallery.plugin/admin/galleryContent.ts'
import { validateProductContent } from '../Product.plugin/admin/productContent.ts'
import { validateSpecificationsContent } from '../Specifications.plugin/admin/specificationsContent.ts'
import { validateStepsContent } from '../Steps.plugin/admin/stepsContent.ts'
import { validateCTAContent } from '../CTA.plugin/admin/ctaContent.ts'
import { validateFooterContent } from '../Footer.plugin/admin/footerContent.ts'

export const pluginValidators = {
  Navbar: (content: unknown) =>
    validateNavbarContent(
      content as Parameters<typeof validateNavbarContent>[0],
    ),
  Hero: (content: unknown) =>
    validateHeroContent(content as Parameters<typeof validateHeroContent>[0]),
  FAQ: (content: unknown) =>
    validateFAQContent(content as Parameters<typeof validateFAQContent>[0]),
  Features: (content: unknown) =>
    validateFeaturesContent(
      content as Parameters<typeof validateFeaturesContent>[0],
    ),
  Gallery: (content: unknown) =>
    validateGalleryContent(
      content as Parameters<typeof validateGalleryContent>[0],
    ),
  Product: (content: unknown) =>
    validateProductContent(
      content as Parameters<typeof validateProductContent>[0],
    ),
  Specifications: (content: unknown) =>
    validateSpecificationsContent(
      content as Parameters<typeof validateSpecificationsContent>[0],
    ),
  Steps: (content: unknown) =>
    validateStepsContent(content as Parameters<typeof validateStepsContent>[0]),
  CTA: (content: unknown) =>
    validateCTAContent(content as Parameters<typeof validateCTAContent>[0]),
  Footer: (content: unknown) =>
    validateFooterContent(
      content as Parameters<typeof validateFooterContent>[0],
    ),
} as const
