// Generated by npm run plugins:sync. Do not edit manually.
export const pluginCatalog = [
  {
    manifest: {
      id: 'navbar',
      name: 'Navbar',
      category: 'Navigation',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'header',
      defaults: {
        title: 'Navigation',
        body: 'Links to the main pages.',
        links: [],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'links', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'hero',
      name: 'Hero',
      category: 'Hero',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'hero',
      defaults: {
        title: 'A clear starting point for your product.',
        body: 'A structural preview of the selected Blueprint.',
        actionLabel: 'Learn more',
        actionHref: '',
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'actionLabel', type: 'text', required: true },
        { name: 'actionHref', type: 'url', required: false },
      ],
    },
  },
  {
    manifest: {
      id: 'faq',
      name: 'FAQ',
      category: 'FAQ',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: {
        title: 'FAQ',
        body: 'Answer common questions.',
        questions: [
          {
            question: 'How does it work?',
            answer: 'Explain the main steps in a few sentences.',
          },
        ],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'questions', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'features',
      name: 'Features',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: {
        title: 'Features',
        body: 'Describe your key benefits.',
        items: [
          { title: 'Fast setup', body: 'Describe the first benefit.' },
          { title: 'Flexible design', body: 'Describe the second benefit.' },
          { title: 'Ready to grow', body: 'Describe the third benefit.' },
        ],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'items', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'gallery',
      name: 'Gallery',
      category: 'Media',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: { title: 'Gallery', body: 'Showcase your images.', images: [] },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'images', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'product',
      name: 'Product',
      category: 'Commerce',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: {
        title: 'Our products',
        body: 'Published products from the CMS catalog appear here.',
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'specifications',
      name: 'Specifications',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: {
        title: 'Specifications',
        body: 'Technical information about the product.',
        specifications: [
          { label: 'Dimensions', value: 'Add the product dimensions.' },
          { label: 'Weight', value: 'Add the product weight.' },
          { label: 'Materials', value: 'List the main materials.' },
        ],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'specifications', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'steps',
      name: 'Steps',
      category: 'Content',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'content',
      defaults: {
        title: 'How it works',
        body: 'Explain the process one step at a time.',
        items: [
          { title: 'First step', body: 'Describe what the user does first.' },
          { title: 'Second step', body: 'Describe what happens next.' },
          { title: 'Final step', body: 'Describe the expected result.' },
        ],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'items', type: 'list', required: true },
      ],
    },
  },
  {
    manifest: {
      id: 'cta',
      name: 'CTA',
      category: 'Conversion',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'conversion',
      defaults: {
        title: 'Get started',
        body: 'Invite visitors to take action.',
        actionLabel: 'Get started',
        actionHref: '',
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'actionLabel', type: 'text', required: true },
        { name: 'actionHref', type: 'url', required: false },
      ],
    },
  },
  {
    manifest: {
      id: 'footer',
      name: 'Footer',
      category: 'Footer',
      version: '1.0.0',
      supports: ['react'],
      defaultSlot: 'footer',
      defaults: {
        title: 'Footer',
        body: 'Contact and legal links.',
        links: [],
      },
    },
    schema: {
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'body', type: 'textarea', required: true },
        { name: 'links', type: 'list', required: true },
      ],
    },
  },
] as const
