import { readdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { format, resolveConfig } from 'prettier'

const root = resolve(import.meta.dirname, '..')
const pluginsDirectory = resolve(root, 'plugins')
const output = resolve(pluginsDirectory, 'src', 'generatedCatalog.ts')
const checkOnly = process.argv.includes('--check')
const slots = ['header', 'hero', 'content', 'conversion', 'footer']

const directories = (await readdir(pluginsDirectory, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && entry.name.endsWith('.plugin'))
  .map((entry) => entry.name)

const plugins = []
for (const directory of directories) {
  const manifestPath = resolve(pluginsDirectory, directory, 'manifest.json')
  const schemaPath = resolve(pluginsDirectory, directory, 'schema.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  const schema = JSON.parse(await readFile(schemaPath, 'utf8'))

  for (const key of [
    'id',
    'name',
    'category',
    'version',
    'supports',
    'defaultSlot',
  ]) {
    if (manifest[key] === undefined)
      throw new Error(`${directory}: manifest.${key} est requis.`)
  }
  if (!slots.includes(manifest.defaultSlot)) {
    throw new Error(`${directory}: slot ${manifest.defaultSlot} inconnu.`)
  }
  if (!Array.isArray(schema.fields)) {
    throw new Error(`${directory}: schema.fields doit etre un tableau.`)
  }
  plugins.push({ directory, manifest, schema })
}

plugins.sort(
  (left, right) =>
    slots.indexOf(left.manifest.defaultSlot) -
      slots.indexOf(right.manifest.defaultSlot) ||
    left.manifest.name.localeCompare(right.manifest.name),
)

const imports = plugins
  .map(
    ({ directory, manifest }, index) =>
      `import preview${index} from '../${directory}/preview.svg?url' // ${manifest.name}`,
  )
  .join('\n')
const entries = plugins
  .map(
    ({ manifest, schema }, index) => `  {
    manifest: ${JSON.stringify(manifest)},
    schema: ${JSON.stringify(schema)},
    previewImage: preview${index},
  },`,
  )
  .join('\n')
const prettierConfig = (await resolveConfig(output)) ?? {}
const source = await format(
  `// Generated by npm run plugins:sync. Do not edit manually.\n${imports}\n\nexport const pluginCatalog = [\n${entries}\n] as const\n`,
  { ...prettierConfig, parser: 'typescript' },
)

if (checkOnly) {
  const current = await readFile(output, 'utf8').catch(() => '')
  if (current !== source) {
    throw new Error(
      'Le catalogue de plugins est obsolete. Executez npm run plugins:sync.',
    )
  }
} else {
  await writeFile(output, source, 'utf8')
  console.log(
    `${plugins.length} plugins synchronises dans plugins/src/generatedCatalog.ts`,
  )
}
