import { readdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { format, resolveConfig } from 'prettier'

const root = resolve(import.meta.dirname, '..')
const pluginsDirectory = resolve(root, 'plugins')
const catalogOutput = resolve(pluginsDirectory, 'src', 'generatedCatalog.ts')
const previewsOutput = resolve(pluginsDirectory, 'src', 'generatedPreviews.ts')
const checkOnly = process.argv.includes('--check')
const slots = ['header', 'hero', 'content', 'conversion', 'footer']

const directories = (await readdir(pluginsDirectory, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory() && entry.name.endsWith('.plugin'))
  .map((entry) => entry.name)

const plugins = []
for (const directory of directories) {
  const manifestPath = resolve(pluginsDirectory, directory, 'manifest.json')
  const schemaPath = resolve(pluginsDirectory, directory, 'schema.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  const schema = JSON.parse(await readFile(schemaPath, 'utf8'))

  for (const key of [
    'id',
    'name',
    'category',
    'version',
    'supports',
    'defaultSlot',
    'defaults',
  ]) {
    if (manifest[key] === undefined)
      throw new Error(`${directory}: manifest.${key} est requis.`)
  }
  if (!slots.includes(manifest.defaultSlot)) {
    throw new Error(`${directory}: slot ${manifest.defaultSlot} inconnu.`)
  }
  if (!Array.isArray(schema.fields)) {
    throw new Error(`${directory}: schema.fields doit etre un tableau.`)
  }
  if (
    schema.fields.some(
      (field) =>
        typeof field.name !== 'string' ||
        typeof field.label !== 'string' ||
        field.label.trim() === '' ||
        !['text', 'textarea', 'url', 'list'].includes(field.type) ||
        typeof field.required !== 'boolean',
    )
  ) {
    throw new Error(
      `${directory}: un champ du schema est incomplet ou inconnu.`,
    )
  }
  for (const field of schema.fields.filter(
    (candidate) => candidate.type === 'list' && 'itemFields' in candidate,
  )) {
    if (
      typeof field.itemLabel !== 'string' ||
      typeof field.addLabel !== 'string' ||
      !Number.isInteger(field.minItems) ||
      !Number.isInteger(field.maxItems) ||
      field.minItems < 0 ||
      field.maxItems < field.minItems ||
      !Array.isArray(field.itemFields) ||
      field.itemFields.some(
        (itemField) =>
          typeof itemField.name !== 'string' ||
          typeof itemField.label !== 'string' ||
          !['text', 'textarea', 'url'].includes(itemField.type) ||
          typeof itemField.required !== 'boolean' ||
          (itemField.asset !== undefined && itemField.asset !== 'image'),
      ) ||
      typeof field.defaultItem !== 'object' ||
      field.defaultItem === null
    ) {
      throw new Error(`${directory}: configuration de liste invalide.`)
    }
    const itemFieldNames = field.itemFields
      .map((itemField) => itemField.name)
      .sort()
    const defaultItemNames = Object.keys(field.defaultItem).sort()
    if (JSON.stringify(itemFieldNames) !== JSON.stringify(defaultItemNames)) {
      throw new Error(
        `${directory}: defaultItem doit correspondre aux sous-champs de la liste.`,
      )
    }
  }
  if (
    typeof manifest.defaults !== 'object' ||
    manifest.defaults === null ||
    Array.isArray(manifest.defaults)
  ) {
    throw new Error(`${directory}: manifest.defaults doit etre un objet.`)
  }
  const fieldNames = schema.fields.map((field) => field.name).sort()
  const defaultNames = Object.keys(manifest.defaults).sort()
  if (JSON.stringify(fieldNames) !== JSON.stringify(defaultNames)) {
    throw new Error(
      `${directory}: les valeurs initiales doivent correspondre exactement au schema.`,
    )
  }
  plugins.push({ directory, manifest, schema })
}

plugins.sort(
  (left, right) =>
    slots.indexOf(left.manifest.defaultSlot) -
      slots.indexOf(right.manifest.defaultSlot) ||
    left.manifest.name.localeCompare(right.manifest.name),
)

const previewImports = plugins
  .map(
    ({ directory, manifest }, index) =>
      `import preview${index} from '../${directory}/preview.svg?url' // ${manifest.name}`,
  )
  .join('\n')
const catalogEntries = plugins
  .map(
    ({ manifest, schema }) => `  {
    manifest: ${JSON.stringify(manifest)},
    schema: ${JSON.stringify(schema)},
  },`,
  )
  .join('\n')
const previewEntries = plugins
  .map(
    ({ manifest }, index) =>
      `  ${JSON.stringify(manifest.name)}: preview${index},`,
  )
  .join('\n')
const prettierConfig = (await resolveConfig(catalogOutput)) ?? {}
const catalogSource = await format(
  `// Generated by npm run plugins:sync. Do not edit manually.\nexport const pluginCatalog = [\n${catalogEntries}\n] as const\n`,
  { ...prettierConfig, parser: 'typescript' },
)
const previewsSource = await format(
  `// Generated by npm run plugins:sync. Do not edit manually.\n${previewImports}\n\nexport const pluginPreviewImages = {\n${previewEntries}\n} as const\n`,
  { ...prettierConfig, parser: 'typescript' },
)

if (checkOnly) {
  const [currentCatalog, currentPreviews] = await Promise.all([
    readFile(catalogOutput, 'utf8').catch(() => ''),
    readFile(previewsOutput, 'utf8').catch(() => ''),
  ])
  if (currentCatalog !== catalogSource || currentPreviews !== previewsSource) {
    throw new Error(
      'Le catalogue de plugins est obsolete. Executez npm run plugins:sync.',
    )
  }
} else {
  await Promise.all([
    writeFile(catalogOutput, catalogSource, 'utf8'),
    writeFile(previewsOutput, previewsSource, 'utf8'),
  ])
  console.log(
    `${plugins.length} plugins synchronises dans plugins/src/generatedCatalog.ts`,
  )
}
